Repository jupyter-book/jupyter-book, pull requests merged in 2024-11, with the labels that each got.

#2245 🪐 Make jupyter a dependency
  pyproject.toml
Labels: next

#2244 📙 Next documentation improvements
  docs/about/history.md
  docs/about/toolchain.md
  docs/install.md
  docs/myst.yml
  docs/overview.md
  docs/start/build-websites.md
  docs/start/create-content.md
  docs/start/cross-reference.md
  docs/start/export-pdfs.md
  docs/start/init.md
  docs/start/publish.md
  docs/upgrade.md
Labels: next

#2257 🤖 Add jupyter releaser
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .github/workflows/full-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-changelog.yml
  .github/workflows/publish-release.yml
  CHANGELOG.md
Labels: maintenance

#2258 :rock: Bump version to 2.0.0a0
  package-lock.json
  package.json
Labels: maintenance, :arrow_forward: next

#2255 ✏️ Remove references to executablebooks
  README.md
  docs/about/history.md
  docs/upgrade.md
Labels: :arrow_forward: next

#2260 🛠️ Set up Node.js version handling
  package.json
  pyproject.toml
Labels: maintenance

#2261 📦 Install before clean during release
  pyproject.toml
Labels: maintenance, :arrow_forward: next

#2262 📝 Add simple CI testing of CLI version
  .github/workflows/ci.yml
Labels: maintenance, :arrow_forward: next

#2256 📕 Show how you can programmatically include content
  .github/workflows/deploy.yml
  docs/execute/generate-myst.md
  docs/myst.yml
  docs/start.md
  docs/tutorial/execution.md
Labels: documentation, next

#2264 Add a plugin tutorial
  docs/glossary.md
  docs/myst.yml
  docs/plugins/ast.md
  docs/plugins/debug.md
  docs/plugins/directives-and-roles.md
  docs/plugins/media/sandbox-demo.mp4
  docs/src/directives.mjs
  docs/src/landing-page.mjs
  docs/src/xref.mjs
  docs/start.md
  docs/start/install.md
  docs/tutorial/plugins.md
  docs/tutorial/website.md
Labels: next

#2266 Add howto for plugin dependencies
  docs/myst.yml
  docs/plugins/dependencies.md
  docs/tutorial/plugins.md
Labels: documentation, next
