Repository jupyter-book/jupyter-book, pull requests merged in 2025-01, with the labels that each got.

#2285 🖼️ Fix path to images in README
  README.md
  docs/media/images/logo-square.svg
Labels: documentation, next

#2286 🔰 Add badge to docs
  docs/media/images/badge.svg
Labels: documentation, next

#2295 🪢 Loosen PyPI dependencies for nodeenv etc.
  pyproject.toml
Labels: bug, next

#2298 Convert readthedocs pushd to cd
  .readthedocs.yaml
Labels: maintenance

#2299 cd within same command as build for RTD
  .readthedocs.yaml
Labels: maintenance

#2313 🏷️ Set whitelabelling on NPM package rather than Python
  py/jupyter_book/__main__.py
  ts/index.ts
Labels: bug, next
